[basic]
challenge = "0 1 2"
result = "2 1 0"

[addfunc]
challenge = "1 4 +"
result = "0 4 1"

[add]
challenge = "1 2 +!"
result = "3"

[arradd]
challenge = "[1 2 +] !"
result = "3"

[doublefunc]
challenge = "1 2 3 4 [+ +] !"
result = "9 1"

[execiftrue]
challenge = "1 [4 5 6 +] ?!"
result = "11 4"

[execiffalse]
challenge = "0 [4 5 6 +] ?!"
result = ""

[string]
challenge = "\"hello\""
result = "\"hello\""

[concat]
challenge = "\"hello\" \"hi\" concat!"
result = "\"hellohi\""

[comments]
challenge = "\"hello\" (comment test) \"hi\" concat!"
result = "\"hellohi\""

[newvar]
challenge = ":\"hi\" hi"
result = "[]"

[vartest]
challenge = ":\"hi\" [[hi]]!"
result = "[ [] ]"

[depthvar1]
challenge = ":\"hi\" hi:[ 1 2 3 :\"test\" 4 5 6 ] hi:test"
result = "[] [ 6 5 4 3 2 1 ]"

[depthvar2]
challenge = """:\"hi\" hi:[ 1 2 3 4 5 6 ] hi"""
result = "[ 6 5 4 3 2 1 ] [ 6 5 4 3 2 1 ]"

[internalbreak]
challenge = "1 2 3 [4 5 breakpoint!]"
result = """[BREAK : 5 4 ]
  [ 5 4 ]  3 2 1"""

[shallowbang]
challenge = "[1 2 3 + [4 5 +]]!"
result = "[ 0 5 4 ]  5 1"

[deepbang]
challenge = "[1 2 3 + [4 5 +] !!] !"
result = "9 5 1"

[triple]
challenge = "[1 2 3 + [4 5 +] !!!] !! ! !"
result = "9 5 1"

[link]
challenge = ":\"hi\" hi [1 2 3 + [4 5 +] !!!] link !"
result = ""

[storelink]
challenge = ":\"hi\" hi [1 2 3] link ! hi lunk !"
result = "[ 3 2 1 ]"

[pull0]
challenge = "1 pull!"
result = ""

[pull]
challenge = "1 2 3 pull!"
result = "2 1"

[twicepull]
challenge = "1 2 3 [pull pull]!"
result = "1"

[condpull]
challenge = "1 2 1 [pull]?!"
result = "1"

[addclosure]
challenge = """
  :"n" 
  n literal entype!
  1 2 n:+ !
"""
result = "3"

[clone]
challenge = """
  :"n"
  n literal entype!   
  n 4 set! clone!
  n n 9 +! set!
  n (n = 4)
  2 push! (clone = 13)
"""
result = "4 13 13 4"

# [askfornum]
# challenge = ":\"hi\" hi:2"
# result = "2"