[nothing]
challenge = ""
result = ""

[one]
challenge = "1"
result = "1"

[basic]
challenge = "0 1 2"
result = "0 1 2"

[addfunc]
challenge = "1 4 +"
result = "1 4 +"

[declare]
challenge = """
  "hi" declare!
  "hello" declare!
"""
result = "hi:[] hello:[]"

[add]
challenge = "1 2 + !"
result = "3"

[equal]
challenge = "1 2 == ! 1 1 == !"
result = "0 1"

[not]
challenge = "1 2 not ! 0 not!"
result = "1 0 1"

[and]
challenge = "1 2 and! 0 1 and! 0 0 and!"
result = "1 0 0"

[or]
challenge = "1 2 or! 1 0 or! 0 1 or! 0 0 or!"
result = "1 1 1 0"

[arradd]
challenge = "[1 2 + !!] !"
result = "3"

[doublefunc]
challenge = "1 2 3 4 [+ +] run !"
result = "1 9"

[execiftrue]
challenge = "1 [4 5 6 + !!] ? !"
result = "4 11"

[execiffalse]
challenge = "0 [4 5 6 + !!] ? !"
result = ""

[isempty]
challenge = """
  [] isempty! [1 2 3] ? !
  [1] isempty! [4 5 6] ? !
"""
result = "1 2 3"

[string]
challenge = "\"hello\""
result = "\"hello\""

[concat]
challenge = "\"hello\" \"hi\" concat!"
result = "\"hellohi\""

[comments]
challenge = "\"hello\" (comment test) \"hi\" concat!"
result = "\"hellohi\""

[newvar]
challenge = ":\"hi\""
result = "hi:[]"

[vartest]
challenge = ":\"hi\" [[hi]]!"
result = "hi:[]  [ hi:[] ]  "

[depthvar1]
challenge = ":\"hi\" pull! hi:[ 1 2 3 :\"test\" 4 5 6 ] hi:test"
result = "[ 1 2 3 test:[] 4 5 6 ] test:[]  "

[depthvar2]
challenge = """:\"hi\" pull! hi:[ 1 2 3 4 5 6 ] hi"""
result = "[ 1 2 3 4 5 6 ] [ 1 2 3 4 5 6 ]  "

[depthvar3]
challenge = """
  :\"hi\" pull! hi:[ 1 2 3 :\"test\" 4 5 6 ]
  hi:test:[ :\"okay\" ]
  hi:test:okay
"""
result = "[ 1 2 3 [ okay:[] ] 4 5 6 ] [ okay:[] ] okay:[] "

[depthvar3fail]
challenge = """
  "hi" declare! hi:[ 1 2 3 "test" declare! 4 5 6 ]
  hi:test:[ "okay" declare! ]
  hi:test:okaye
"""
result = """
<4:91>:Couldn't find string 'okaye' in scope 'test'
  "hi" declare! hi:[ 1 2 3 "test" declare! 4 5 6 ]
  hi:test:[ "okay" declare! ]
  hi:test:!>>>>>okaye
"""

[internalbreak]
challenge = "1 2 3 [4 5 breakpoint!]"
result = """[BREAK : 4 5 ]
 1 2 3  [ 4 5 ]"""

[readdouble]
challenge = "!!"
result = "!!"

[shallowbang]
challenge = "[1 2 3 + !! [4 5 +]]!"
result = "1 5  [ 4 5 + ] "

[deepbang]
challenge = "[1 2 3 + !! [4 5 + !!] !!] !"
result = "1 5 9"

[successorcheck]
challenge = "!!! !"
result = "!!"

[triple]
challenge = "[1 2 3 + !! [4 5 + !!] !!! ] !! ! !"
result = "1 5 9"

[depth4]
challenge = "[ 1 [ 2 [ 3 [4] !!] !!] !!] !"
result = "1 2 3 4"

[depth4_2]
challenge = "[ 1 [ 2 [ 3 [4] !!] !!] ] !"
result = "1  [ 2  [ 3  [ 4 ]  !! ]  !! ]  "

[link]
challenge = ":\"hi\" hi [1 2 3 + [4 5 +] !!!] <- !"
result = "hi:[]"

[storelink]
challenge = ":\"hi\" hi [1 2 3] <- ! hi -> !"
result = "hi:[]  [ 1 2 3 ] "

[pull0]
challenge = "1 pull!"
result = ""

[pull]
challenge = "1 2 3 pull!"
result = "1 2"

[twicepull]
challenge = "1 2 3 [pull pull] run!"
result = "1"

[condpull]
challenge = "1 2 1 [[pull pull] run!!]?!"
result = ""

[condpull2]
challenge = "1 2 1 pull ?!"
result = "1"

[verboseclosure]
challenge = """
  "n" declare! literal!
  5 =!
  [n literal:+ !!] "ok" declare! assign!
  1 ok!
  2 ok!
  n 7 =!
  3 ok!
"""
result = "7 6 7 7 10"

[literaladd]
challenge = """
  "n" declare! literal! pull!
  1 2 literal:+ !
"""
result = "3"

[addclosure]
challenge = """
  "n" declare! literal! pull!
  n 5 =! pull!
  1 2 n:+ !
"""
result = "3"

[addclosure2]
challenge = """
  "n" declare! literal! pull!
  1 2 [n:+!!] !
"""
result = "3"

[implicit]
challenge = """
  "n" declare! literal!
  n:[
    [n + !!] "+" declare! assign!
  ] pull!
  n 2 =! pull!
  1 n:+!
  10 n:+!
  1 2 +!
"""
result = """2 3 12 3"""

[replicate]
challenge = """
  "n" declare! literal!
  4 =! 1 replicate! !
  n n 9 +! =!
  n (n = 4)
  2 push! (replicate = 13)
"""
result = "4 13 13 4"

[assign]
challenge = """
  1 "a" declare! assign !
  a literal!
"""
result = "1"

[shallowreplicate]
challenge = """
  "n" declare! "m" declare!
  m:"z"
  literal!
  2 =!
  m:z
  m:z 1 replicate! ! "b" declare! assign!
  (the replicate isn't deep:
    references to variables are not copied)
  m 1 replicate! ! "o" declare! assign!
  o:z o:z 2 +! =!
  o:z b
"""
result = "n:[] m:[] 4 4 4 4 2"

[fib]
challenge = """
  [0 push 2 swap +] "fib" declare! assign!
  1 1
  fib run! fib run! fib run! fib run! fib run!
"""
result = "8 13"

[factorial]
challenge = """
  "factorial" declare!
  [
    0 push!! 1 -!!
    0 push!!
    0 push!!
    not!! pull ?!!
    [factorial ->!! !!] ?!!
    *!!
  ] <-!
  factorial array! pull!

  1 5 factorial ->! !

  1 8 factorial ->! !
"""
result = "120 40320"

[rv64]
challenge = "`.quad t0`"
result = "\".quad t0\""

[pusharray]
challenge = """
  "arr" declare!
  array!
  ["hi"] <-!
  arr:[4 5 6] pull!
  arr:[1 2] pull!
  arr:[pull! push!]
"""
result = "[ 4 5 6 5 ]"

[mapvect]
challenge = """
  "arr" declare! pull!
  arr:[1 2 3 4] [1 + !!] map!
  arr
"""
result = "[ 2 3 4 5 ]  [ 1 2 3 4 ] "

[identmap]
challenge = """
  "arr" declare! pull!
  "n" declare! literal! 4 =! pull!
  arr:[1 2 3 n]
  [] map!
  "arr2" declare! assign!
  arr2
  arr
  arr [1 replicate!! !!] map!
  n n 1 +! =!
"""
result = "[ 1 2 3 5 ]  [ 1 2 3 5 ]  [ 1 2 3 4 ]  5"

[replicatemap]
challenge = """
  "arr" declare! pull!
  arr:[1 2 3 4]
  [1 replicate !! !!] map!
  "arr2" declare! assign!
  arr2:[+!]
  arr
"""
result = "[ 1 2 7 ]  [ 1 2 3 4 ]"

[infunc]
challenge = """
  "stk" declare!
  [1 0 push !!] in !
  stk + in!
  stk
"""
result = "[ 2 ] [ 2 ] [ 2 ]"

[exit]
challenge = """
  exit!
  1
"""
result = "[BREAK]"

[exit2]
challenge = """
  1 2 3 4
  1 2 + !
  exit!
  9 8 7 6 5 4
"""
result = """
[BREAK : 1 2 3 4 3 ]
<2:0>:function errored
!>>>>>"""

[getlength]
challenge = """
  :"arr" array! pull!
  length!
  arr:[1] length in! pullfrom!
  arr:[1 2] length in! pullfrom!
"""
result = "0 1 3"

[pullfrom]
challenge = """
  [1 2 3 4] pullfrom!
  [1] pullfrom!
"""
result = "4 1"

[foldarr]
challenge = """
  "arr" declare! pull!
  "n" declare! array! pull!
  arr:[1 2 3 4]
  [n [+] in!!] map!
  arr n apply!
"""
result = "10"

[args]
challenge = """
  "func" declare! array! pull!
  "arr" declare! array! pull!
  func:[1 +!! "a" declare! assign!!] pull!
  arr:[1 2 3 4]
  [arr func in!! pull!!] "wrap" declare! assign!
  array! pull!
  arr [1 replicate!! !!] map!
  wrap! arr [1 replicate!! !!] map!
  wrap! arr [1 replicate!! !!] map!
  wrap! arr [1 replicate!! !!] map!
  arr:a
"""
result = "[ 1 2 3 4 ]   [ 1 2 3 ]   [ 1 2 ]   [ 1 ]  3 "

[object]
challenge = """
  "type" declare! pull!
  type:[
    "construct" declare! pull!
    construct:[
      "this" declare! type <-! pull!
    ]
  ]
  type:construct:this ->! [1] in! pull!
  type:construct:this ->! ["a" declare! assign!!] in! pull!
  type:a
"""
result = "[ construct:[] ] 1"

[build]
challenge = """
  "arr" declare! array!
  [1 2 3 [+]] in! pull!
  arr
"""
result = "[ 1 2 3  [ + ]  ]"

[zip]
challenge = """
  "zip1" declare! array! pull!
  "zip2" declare! array! pull!
  zip1:[1 2 3 4] pull!
  zip2:[5 6 7 8] pull!
  zip1 zip2 apply!
"""
result = "1 5 2 6 3 7 4 8"

[foldfunc]
challenge = """
  (this doesn't work, grabbing an extra element, 0,
  from the end of the list.  For multiplication this nukes the result)

  "arr" declare! array! pull!
  arr [1 2 3 4] in! pull!

  "fold" declare! array! pull!

  fold:[
    "farr" declare! array! pull!
    "f" declare! array! pull!
    "v" declare! array! pull!
    
    v -> [farr ->!! [f ->!!] in!! pull!!] map
    [farr] [pull] in pull
    v -> farr -> apply
  ] pull!
  fold:farr [] <-!
  fold:v arr <-!
  fold:f + <-!
  fold run!

  fold:farr [] <-!
  fold:v [8 9 10] <-!
  fold:f - <-!
  fold run!

  fold:farr [] <-!
  fold:v [2 10 9 8 7 6] <-!
  fold:f [1 -!! *!!] <-!
  fold run!
"""
result = "10 -27 0"

[fold2]
challenge = """
  :"fold" pull!
  fold:"f" array! pull!
  fold:"v" array! pull!
  fold:"foldlink" fold <-!
  fold:[
    1 v ->!! length in!! pullfrom!! <!! [
      v ->!! f ->!! in!! pull!! fold:foldlink ->!! !!
    ] ?!!
  ] pull!
  fold array! pull!
  :"arr" array!
  arr:[1 2 3 4] + in! pull!
  fold:v arr <-!
  fold:f + <-!
  fold! !

  arr:[5 4 3 2]
  fold:v arr <-!
  fold:f - <-!
  fold! !

  :"arr2" array! pull!
  arr2:[1 2 5]
  fold:v arr2 <-!
  fold:f [*!! 1 +!!] <-!
  fold! !
"""
result = "10 8 12"

[fold3]
challenge = """
  :"fold" pull!
  fold:"f" array! pull!
  fold:"v" array! pull!
  fold:"inner" array! pull!
  fold:"foldlink" fold:inner <-!
  fold:[
    f 1 swap!! <-!!
    v 1 swap!! <-!!
    inner:[
      1 v ->!! length in!! pullfrom!! <!!
      [
        v ->!! f ->!! in!! pull!!
        fold:foldlink ->!! !!
      ] ? !!
    ] pull!
    inner!!
  ] pull!
  fold array! pull!
  :"arr" array! pull!
  arr:[1 2 3 4] + in! pull!
  arr + fold!
  arr breakpoint!

  arr:[5 4 3 2] pull!
  arr - fold!
  arr

  :"arr2" array! pull!
  arr2:[1 2 5] pull!
  arr2 [*!! 1 +!!] fold!
  arr2
"""
result = """
[BREAK :  [ 10 ]  ]
  [ 8 ]   [ 8 ]   [ 12 ]"""

[typecheck]
challenge = """
  type:"is" array! pull!
  type:is:"a" literal! pull!
  type:is:[
    a 1 swap!! =!! pull!!
    [type:is:a ==!!] map!!
  ] pull!
  [0 2 1] 1
  type:is!
  type:is:a
"""
result = "[ 0 0 1 ]  1"

[typecheck2]
challenge = """
  :"fold" pull!
  fold:"f" array! pull!
  fold:"v" array! pull!
  fold:"foldlink" fold <-!
  fold:[
    1 v ->!! length in!! pullfrom!! <!! [
      v ->!! f ->!! in!! pull!! fold:foldlink ->!! !!
    ] ?!!
  ] pull!
  fold array! pull!

  (there's some toml related issue
  with using hashes in strings,
  so I used 'is' instead)
  type:"is" array! pull!
  type:is:[
      :"a" literal! pull!
      a 1 swap!! =!! pull!!
      [type:is:a ==!!] map!!

      fold:v 1 swap!! <-!!
      fold:f or <-!!
      fold!! fold:v ->!! !!
  ] pull!

  [0 2 0] 1
  type:is!

  [0 1 0 0 1 0] 1
  type:is!

  [1 1 1] 1
  type:is!

  [0x-1 2 4] 1
  type:is!
"""
result = "0 1 1 0"

[explore]
challenge = """
  :"a" explore!
"""
result = """
[BREAK : a:[] ]
"a":
( )
(#:  )
 a:[]
"""

[dir]
challenge = """
  :"a" array! dir!
  a:[
    :"test"
  ] pull!
  a dir!
"""
result = "[  [ \"#\" array:[] ]  ]   [  [ \"#\" array:[] ]   [ \"test\" test:[] ]  ]"

[has]
challenge = """
  :"a" pull!
  a:[
    :"b"
  ] pull!
  a "b" has!
  a "c" has!
"""
result = "1 0"

[has2]
challenge = """
  (this is a proof of concept, runs in O of n, 
  it's better to just use the inbuilt "has",
  to take advantage of hashing)

  :"fold" pull!
  fold:"f" array! pull!
  fold:"v" array! pull!
  fold:"foldlink" fold <-!
  fold:[
    1 v ->!! length in!! pullfrom!! <!! [
      v ->!! f ->!! in!! pull!! fold:foldlink ->!! !!
    ] ?!!
  ] pull!
  fold array! pull!

  :"is" array! pull!
  is:[
    :"a" literal! pull!
    a 1 swap!! =!! pull!!
    [a ==!!] map!!

    fold:v 1 swap!! <-!!
    fold:f and <-!!
    fold!! fold:v ->!! !!
  ] pull!

  "hasvar" declare! array! pull!
  hasvar:[
      "a" declare! array! pull!
      a 1 swap!! string:expand!! <-!!
      dir!!
      [
        !! pull!!
        string:expand!!
        a ->!! !! is!!
      ] map !!

      fold:v 1 swap!! <-!!
      fold:f or <-!!
      fold!! fold:v ->!! !!
  ] pull!
  :"a"
  a:[:"b"] pull!
  "b" hasvar!
  a "c" hasvar!
"""
result = "1 0"

