[nothing]
challenge = ""
result = ""

[one]
challenge = "1"
result = "1"

[basic]
challenge = "0 1 2"
result = "2 1 0"

[addfunc]
challenge = "1 4 +"
result = "+ 4 1"

[add]
challenge = "1 2 + !"
result = "3"

[arradd]
challenge = "[1 2 +] !"
result = "3"

[doublefunc]
challenge = "1 2 3 4 [+ +] !"
result = "9 1"

[execiftrue]
challenge = "1 [4 5 6 +] ?!"
result = "11 4 1"

[execiffalse]
challenge = "0 [4 5 6 +] ?!"
result = ""

[string]
challenge = "\"hello\""
result = "\"hello\""

[concat]
challenge = "\"hello\" \"hi\" concat!"
result = "\"hellohi\""

[comments]
challenge = "\"hello\" (comment test) \"hi\" concat!"
result = "\"hellohi\""

[newvar]
challenge = ":\"hi\""
result = "[]"

[vartest]
challenge = ":\"hi\" [[hi]]!"
result = "[ [] ]  []"

[depthvar1]
challenge = ":\"hi\" ,! hi:[ 1 2 3 :\"test\" 4 5 6 ] hi:test"
result = "[] [ 6 5 4 [] 3 2 1 ]"

[depthvar2]
challenge = """:\"hi\" ,! hi:[ 1 2 3 4 5 6 ] hi"""
result = "[ 6 5 4 3 2 1 ] [ 6 5 4 3 2 1 ]"

[depthvar3]
challenge = """
  :\"hi\" ,! hi:[ 1 2 3 :\"test\" 4 5 6 ]
  hi:test:[ :\"okay\" ]
  hi:test:okay
"""
result = "[] [ [] ] [ 6 5 4 [ [] ] 3 2 1 ]"

[depthvar3fail]
challenge = """
  :\"hi\" hi:[ 1 2 3 :\"test\" 4 5 6 ]
  hi:test:[ :\"okay\" ]
  hi:test:okaye
"""
result = """
<4:67>:Couldn't find string 'okaye' in scope 'test'
  :"hi" hi:[ 1 2 3 :"test" 4 5 6 ]
  hi:test:[ :"okay" ]
  hi:test:!>>>>>okaye
"""

[internalbreak]
challenge = "1 2 3 [4 5 breakpoint!]"
result = """[BREAK : 5 4 ]
  [ 5 4 ]  3 2 1"""

[readdouble]
challenge = "!!"
result = "!!"

[shallowbang]
challenge = "[1 2 3 + [4 5 +]]!"
result = "[ + 5 4 ]  5 1"

[deepbang]
challenge = "[1 2 3 + [4 5 +] !!] !"
result = "9 5 1"

[triple]
challenge = "[1 2 3 + [4 5 +] !!! ] !! ! !"
result = "9 5 1"

[depth4]
challenge = "[ 1 [ 2 [ 3 [4] !!] !!] !!] !"
result = "4 3 2 1"

[depth4_2]
challenge = "[ 1 [ 2 [ 3 [4] !!] !!] ] !"
result = "[ !!  [ !!  [ 4 ]  3 ]  2 ]  1"

[link]
challenge = ":\"hi\" hi [1 2 3 + [4 5 +] !!!] <- !"
result = "[]"

[storelink]
challenge = ":\"hi\" hi [1 2 3] <- ! hi -> !"
result = "[ 3 2 1 ]  []"

[pull0]
challenge = "1 ,!"
result = ""

[pull]
challenge = "1 2 3 ,!"
result = "2 1"

[twicepull]
challenge = "1 2 3 [, ,]!"
result = "1"

[condpull]
challenge = "1 2 1 [, ,]?!"
result = "1"

[condpull2]
challenge = "1 2 1 , ?!"
result = "2 1"

[verboseclosure]
challenge = """
  :"n" literal entype!
  5 =!
  [n [literal:+]!!] "ok" assign!
  1 ok!
  2 ok!
  n 7 =!
  3 ok!
"""
result = "10 7 7 6 7"

[literaladd]
challenge = """
  :"n" literal entype! ,!
  1 2 literal:+ !
"""
result = "3"

[addclosure]
challenge = """
  :"n" literal entype! ,!
  1 2 n:+ !
"""
result = "3"

[addclosure2]
challenge = """
  :"n" literal entype! ,!
  1 2 [n:+] !
"""
result = "3"

[implicit]
challenge = """
  :"n" literal entype!
  n:[
    {n +} "+" assign!
  ] ,!
  n 2 =! ,!
  1 n:+!
  10 n:+!
  1 2 +!
"""
result = """3 12 3 2"""

[clone]
challenge = """
  :"n" literal entype!
  4 =! clone!
  n n 9 +! =!
  n (n = 4)
  2 ;! (clone = 13)
"""
result = "4 13 13 4"

[assign]
challenge = """
  1 "a" assign !
  a literal entype!
"""
result = "1"

[shallowclone]
challenge = """
  :"n" :"m"
  m:"z"
  literal entype!
  2 =!
  m:z
  m:z clone! "b" assign!
  (the clone isn't deep:
    references to variables are not copied)
  m clone! "o" assign!
  o:z o:z 2 +! =!
  o:z b
"""
result = "2 4 4 4 4 [] []"

[fib]
challenge = """
  [[0 ; 2 swap]!! +!!] "fib" assign!
  1 1
  fib! fib! fib! fib! fib!
"""
result = "13 8"

[factorial]
challenge = """
  :"factorial"
  [
    0 ; 1 -
    [factorial ->] ?!!
    *
  ] <-!
  factorial array entype! ,!

  1 5 factorial ->! !
"""
result = "120"

[rv64]
challenge = "`.quad t0`"
result = "\".quad t0\""

[pusharray]
challenge = """
  :"arr"
  array entype!
  ["hi"] <-!
  arr:[4 5 6] ,!
  arr:[1 2] ,!
  arr:[,! ;!]
"""
result = "[ 5 6 5 4 ]"