breakpoints = [
    "BREAKPOINT",
    "errorexit",
    "addnode",
    "execfunc",
    "forj.cpp:exec",
    # "8",
    # "forj.cpp:265",
    # "225",
    # "forj.cpp:95",
]
displays = [
    "*W->peek(0)",
    # "lines",
    # "i",
]