breakpoints = [
    # "main",
    # "main.cpp:breakpointhelper",
    # "errorexit",
    # "forj.cpp:debug",
    # "forj.cpp:114",
    # "addmap",
    # "getmap",
    "main",
    # "findstr",
    # "assign",
    "forj.cpp:debug",
    # "8",
    # "forj.cpp:265",
    # "225",
    # "forj.cpp:95",
]
displays = [
    # "*W->peek(0)",
    # "lines",
    # "i",
]