[default]
    breakpoints = [
        # "_start",
        "enterkernel",
        # "initheap",
        # "printarr",
        # "addmap",
        # "parsetok",
        # "findoneof",
        # "searchvch",
        "mainc",
        # "tarraybang",
        # "printarr",
        # "splitstrat",
        # "pushstr",
        # "findstr",
        # "alloc",
        # "alloctest",
        # "reclaim",
        "mtrap",
        # "addmap",
        # "getmap",
        # "identbreak",
        # "identloop",
        # "virtualtophysical",
        # "v2ploop",
    ]
    displays = [
        # "/128xw 0x0000000010008000", # virtio drive
        # "/x $sp",
        # "/x $mstatus",
        # "/i $pc",
        "/x $mcause",
        # "/x $a0",
        # "/x $t0",
        # "/x $t1",
        # "/x $t2",
        # "/x $t3",
        # "/x $t4",
        # "/x $t5",
        # "/x $t6",
        # "/x $satp",
        "/1xh uservalue1",
        "/1xh uservalue2",
        "/1xh uservalue3",
        # "/x $sp",
        # "/16xg mstack-0x70",
        # "/32xg 0x0000000087fff000-0x1c*8",
        # "/64xg 0x0000000087fff000-0x1c*8*2",
        # "printheap()"
        # "/8xg 0x087ffe908-0x02*8",
        # "/8xg 0x087ffe9c0-0x02*8",
        # "/8xg 0x87ffee50-0x02*8",
        # "*0x2004000",
        # "*0x200BFF8",
        # "/16xg threadstore",
        # # "/16xg pagestart",
        # # "/16xg page2",
        # # "/16xg page3",
    ]
    runs = """"""
    result = []

[timer]
    breakpoints = [
        "mtrap",
    ]
    displays = [
        "/x $mcause",
        "*0x2004000",
        "*0x200BFF8",
    ]
    runs = """
        c
        c
    """
    result = [
        "mcause = 0x8000000000000007",
        "*0x2004000 = 50000",
        "*0x200BFF8 = 5",
        "*0x2004000 = 130000",
        "*0x200BFF8 = 13",
        "*0x2004000 = 210000",
        "*0x200BFF8 = 21"
    ]

