[default]
    breakpoints = [
        "_start",
        "enterkernel",
        # "pageloop",
        "mtrap",
        # "identbreak",
        # "identloop",
        # "virtualtophysical",
        # "v2ploop",
    ]
    displays = [
        # "/x $sp",
        # "/x $mstatus",
        # "/8gx mstack",
        # "/i $pc",
        "/i $mepc",
        "/x $mcause",
        "/x $a0",
        "/x $t0",
        "/x $t1",
        "/x $t2",
        "/x $t3",
        "/x $t4",
        "/x $t5",
        "/x $t6",
        # "/x $satp",
        "/1xg uservalue1",
        "/1xg uservalue2",
        "/1xg uservalue3",
        # "*0x2004000",
        # "*0x200BFF8",
        # "/16xg pagestart",
        # "/16xg page2",
        # "/16xg page3",
        # "/xb 0x10000000", # uart regs
        # "/xb 0x10000001", # uart regs
        # "/xb 0x10000002", # uart regs
        # "/xb 0x10000003", # uart regs
        # "/xb 0x10000004", # uart regs
        # "/xb 0x10000005"  # uart regs
    ]
    runs = """"""
    result = []

[timer]
    breakpoints = [
        "mtrap",
    ]
    displays = [
        "/x $mcause",
        "*0x2004000",
        "*0x200BFF8",
    ]
    runs = """
        c
        c
    """
    result = [
        "mcause = 0x8000000000000007",
        "*0x2004000 = 50000",
        "*0x200BFF8 = 5",
        "*0x2004000 = 130000",
        "*0x200BFF8 = 13",
        "*0x2004000 = 210000",
        "*0x200BFF8 = 21"
    ]

